# Generated by Django 6.0.2 on 2026-02-24 21:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('WISHLIST', 'Wishlist'), ('APPLIED', 'Applied'), ('OA', 'Online Assessment'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer'), ('REJECTED', 'Rejected')], default='WISHLIST', max_length=20)),
                ('applied_date', models.DateField()),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='tracker_app_user_id_1e1e0c_idx'), models.Index(fields=['status'], name='tracker_app_status_d66eff_idx'), models.Index(fields=['user', 'status'], name='tracker_app_user_id_368621_idx')],
            },
        ),
    ]
